### ISSUE TITLE
Добавить отображение статистики

### ISSUE THREAD

**Issue by thewizardplusplus** [thewizardplusplus/wizard-budget#46]
- [x] #16 &mdash; отображение статистики в виде графиков;
- [x] #43 &mdash; отображение списка выбранных тегов;
- [x] #45 &mdash; выбор диапазона сбора статистики;
- [x] #44 &mdash; вывод общей суммы расходов;
- [x] #52 &mdash; скрытие кнопки добавления.
