### ISSUE TITLE
Добавить список планируемых покупок

### ISSUE THREAD

**Issue by thewizardplusplus** [thewizardplusplus/wizard-budget#9]
- [x] #31 &mdash; CRUD-операции;
- [x] #32 &mdash; сортировка drag-n-drop;
- [x] бекапы:
  - [x] #33 &mdash; сохранение;
  - [x] #34 &mdash; восстановление;
- [x] автоматическая покупка:
  - [x] #35 &mdash; смена состояния;
  - [x] #36 &mdash; поддержка в тегах.
